package com.discgolf.in_the_bag.suggestions;

import java.util.List;

public enum DiscCategory {
    UNDERSTABLE_PUTT_APPROACH,
    UNDERSTABLE_MIDRANGE,
    UNDERSTABLE_FAIRWAY_6,
    UNDERSTABLE_FAIRWAY_7,
    UNDERSTABLE_FAIRWAY_8,
    UNDERSTABLE_FAIRWAY_9,
    UNDERSTABLE_DRIVER,

    STABLE_PUTT_APPROACH,
    STABLE_MIDRANGE,
    STABLE_FAIRWAY_6,
    STABLE_FAIRWAY_7,
    STABLE_FAIRWAY_8,
    STABLE_FAIRWAY_9,
    STABLE_DRIVER,

    OVERSTABLE_APPROACH,
    OVERSTABLE_MIDRANGE,
    OVERSTABLE_FAIRWAY_6,
    OVERSTABLE_FAIRWAY_7,
    OVERSTABLE_FAIRWAY_8,
    OVERSTABLE_FAIRWAY_9,
    OVERSTABLE_DRIVER;



    // Order of disc categories to check for when there are no special cases
    public static final List<DiscCategory> CHECK_ORDER_SIMPLE = List.of(
            STABLE_PUTT_APPROACH, STABLE_MIDRANGE, UNDERSTABLE_FAIRWAY_7, OVERSTABLE_MIDRANGE, STABLE_FAIRWAY_7,
            OVERSTABLE_APPROACH, UNDERSTABLE_FAIRWAY_9, STABLE_FAIRWAY_9, UNDERSTABLE_DRIVER, OVERSTABLE_FAIRWAY_7,
            OVERSTABLE_FAIRWAY_9, STABLE_DRIVER, OVERSTABLE_DRIVER
    );

    // Order of disc categories to check for when there is an Understable Putt & Approach disc in the bag (we don't suggest Stable Putt & Approach)
    public static final List<DiscCategory> CHECK_ORDER_FOR_UNDERSTABLE_PUTT_APPROACH = List.of(
            STABLE_MIDRANGE, UNDERSTABLE_FAIRWAY_7, OVERSTABLE_MIDRANGE, STABLE_FAIRWAY_7,
            OVERSTABLE_APPROACH, UNDERSTABLE_FAIRWAY_9, STABLE_FAIRWAY_9, UNDERSTABLE_DRIVER, OVERSTABLE_FAIRWAY_7,
            OVERSTABLE_FAIRWAY_9, STABLE_DRIVER, OVERSTABLE_DRIVER
    );

    // Order of disc categories to check for when there is an Understable Midrange in the bag (Stable Midrange moves up to 6th place in the order)
    public static final List<DiscCategory> CHECK_ORDER_FOR_UNDERSTABLE_MIDRANGE = List.of(
            STABLE_PUTT_APPROACH, UNDERSTABLE_FAIRWAY_7, OVERSTABLE_MIDRANGE, STABLE_FAIRWAY_7,
            OVERSTABLE_APPROACH, STABLE_MIDRANGE, UNDERSTABLE_FAIRWAY_9, STABLE_FAIRWAY_9, UNDERSTABLE_DRIVER,
            OVERSTABLE_FAIRWAY_7, OVERSTABLE_FAIRWAY_9, STABLE_DRIVER, OVERSTABLE_DRIVER
    );

    public static final List<DiscCategory> CHECK_ORDER_FOR_BOTH_EDGE_CASES = List.of(
            UNDERSTABLE_FAIRWAY_7, OVERSTABLE_MIDRANGE, STABLE_FAIRWAY_7, OVERSTABLE_APPROACH,
            STABLE_MIDRANGE, UNDERSTABLE_FAIRWAY_9, STABLE_FAIRWAY_9, UNDERSTABLE_DRIVER,
            OVERSTABLE_FAIRWAY_7, OVERSTABLE_FAIRWAY_9, STABLE_DRIVER, OVERSTABLE_DRIVER
    );

}
