server.port = 8080

# Database connection settings
spring.datasource.url = jdbc:postgresql://localhost:5432/in_the_bag
spring.datasource.username = postgres
spring.datasource.password = postgres
spring.datasource.driver-class-name = org.postgresql.Driver

# Hibernate settings (JPA for PostgreSQL)
spring.jpa.database-platform = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.format_sql = true
spring.sql.init.mode = always

# CORS
cors.allowed-origins = http://localhost:5173

# JWT
jwt.secret = NQgWU6JwkHWtgzventX46K5Ak+sCP4cQ0Bh1XBRmz3E=
